### ISSUE TITLE
Firefox warning

### ISSUE THREAD

**Issue by TeChn4K** [cmartin81/ng-decorators#5]
Hi,

Since using ng-decorators, i get a warning in Firefox (41.0.2) : 

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

Do you know where it comes from ? Is it serious ?

BTW, thank you ! Very useful module :)

> Firefox 41.0.2
> Webpack & Babel

**Comment by cmartin81** [comment]
Thanks for the notice! I'm not sure about the actual impact of the performance. I did a quick search and it seems like it could be something babel is creating while transpiling. Which version of babel are you using?

**Comment by TeChn4K** [comment]
Reproduced on 5.8.29 and 5.8.33.

Babel 6 isn't ready with decorators yet : http://phabricator.babeljs.io/T2645

**Comment by TeChn4K** [comment]
I made an transpile exemple [here](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%2F*%0A%20*%20START%20NG-DECORATORS%20CODE%0A%20*%2F%0Afunction%20Directive%28modules%20%3D%20[]%29%20{%0A%20%20return%20createDecorator%28modules%2C%20makeDirective%29%3B%0A}%0A%0Afunction%20createDecorator%28modules%2C%20makeFunction%29%20{%0A%20%20return%20%28target%29%20%3D%3E%20{%0A%20%20%20%20class%20Clazz%20extends%20target%20{%0A%20%20%20%20%20%20constructor%28...injectedValues%29%20{%0A%20%20%20%20%20%20%20%20super%28...injectedValues%29%3B%0A%20%20%20%20%20%20%20%20modules.forEach%28%28module%2C%20i%29%20%3D%3E%20{%0A%20%20%20%20%20%20%20%20%20%20this[module]%20%3D%20injectedValues[i]%3B%0A%20%20%20%20%20%20%20%20}%29%3B%0A%20%20%20%20%20%20%20%20if%20%28typeof%20this.init%20%3D%3D%3D%20%27function%27%29%20{%0A%20%20%20%20%20%20%20%20%20%20this.init%28%29%3B%0A%20%20%20%20%20%20%20%20}%0A%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20%20%20Clazz.%24inject%20%3D%20modules%3B%0A%0A%20%20%20%20return%20makeFunction%28Clazz%29%3B%0A%20%20}%0A}%0A%0Afunction%20makeDirective%28constructorFn%29%20{%0A%0A%20%20constructorFn%20%3D%20_normalizeConstructor%28constructorFn%29%3B%0A%0A%20%20if%20%28!constructorFn.prototype.compile%29%20{%0A%20%20%20%20%2F%2F%20create%20an%20empty%20compile%20function%20if%20none%20was%20defined.%0A%20%20%20%20constructorFn.prototype.compile%20%3D%20%28%29%20%3D%3E%20{%0A%20%20%20%20}%3B%0A%20%20}%0A%0A%20%20var%20originalCompileFn%20%3D%20_cloneFunction%28constructorFn.prototype.compile%29%3B%0A%0A%20%20%2F%2F%20Decorate%20the%20compile%20method%20to%20automatically%20return%20the%20link%20method%20%28if%20it%20exists%29%0A%20%20%2F%2F%20and%20bind%20it%20to%20the%20context%20of%20the%20constructor%20%28so%20%60this%60%20works%20correctly%29.%0A%20%20%2F%2F%20This%20gets%20around%20the%20problem%20of%20a%20non-lexical%20%22this%22%20which%20occurs%20when%20the%20directive%20class%20itself%0A%20%20%2F%2F%20returns%20%60this.link%60%20from%20within%20the%20compile%20function.%0A%20%20_override%28constructorFn.prototype%2C%20%27compile%27%2C%20function%20%28%29%20{%0A%20%20%20%20return%20function%20%28%29%20{%0A%20%20%20%20%20%20originalCompileFn.apply%28this%2C%20arguments%29%3B%0A%0A%20%20%20%20%20%20if%20%28constructorFn.prototype.link%29%20{%0A%20%20%20%20%20%20%20%20return%20constructorFn.prototype.link.bind%28this%29%3B%0A%20%20%20%20%20%20}%0A%20%20%20%20}%3B%0A%20%20}%29%3B%0A%0A%20%20var%20factoryArray%20%3D%20_createFactoryArray%28constructorFn%29%3B%0A%20%20return%20factoryArray%0A}%0A%0Afunction%20_normalizeConstructor%28input%29%20{%0A%20%20var%20constructorFn%3B%0A%0A%20%20if%20%28input.constructor%20%3D%3D%3D%20Array%29%20{%0A%20%20%20%20%2F%2F%0A%20%20%20%20var%20injected%20%3D%20input.slice%280%2C%20input.length%20-%201%29%3B%0A%20%20%20%20constructorFn%20%3D%20input[input.length%20-%201]%3B%0A%20%20%20%20constructorFn.%24inject%20%3D%20injected%3B%0A%20%20}%20else%20{%0A%20%20%20%20constructorFn%20%3D%20input%3B%0A%20%20}%0A%0A%20%20return%20constructorFn%3B%0A}%0A%0Afunction%20_createFactoryArray%28constructorFn%29%20{%0A%20%20%2F%2F%20get%20the%20array%20of%20dependencies%20that%20are%20needed%20by%20this%20component%20%28as%20contained%20in%20the%20%60%24inject%60%20array%29%0A%20%20var%20args%20%3D%20constructorFn.%24inject%20||%20[]%3B%0A%20%20var%20factoryArray%20%3D%20args.slice%28%29%3B%20%2F%2F%20create%20a%20copy%20of%20the%20array%0A%20%20%2F%2F%20The%20factoryArray%20uses%20Angular%27s%20array%20notation%20whereby%20each%20element%20of%20the%20array%20is%20the%20name%20of%20a%0A%20%20%2F%2F%20dependency%2C%20and%20the%20final%20item%20is%20the%20factory%20function%20itself.%0A%20%20factoryArray.push%28%28...args%29%20%3D%3E%20{%0A%20%20%20%20%2F%2Freturn%20new%20constructorFn%28...args%29%3B%0A%20%20%20%20var%20instance%20%3D%20new%20constructorFn%28...args%29%3B%0A%20%20%20%20for%20%28var%20key%20in%20instance%29%20{%0A%20%20%20%20%20%20instance[key]%20%3D%20instance[key]%3B%0A%20%20%20%20}%0A%20%20%20%20return%20instance%3B%0A%20%20}%29%3B%0A%0A%20%20return%20factoryArray%3B%0A}%0A%0Afunction%20_cloneFunction%28original%29%20{%0A%20%20return%20function%20%28%29%20{%0A%20%20%20%20return%20original.apply%28this%2C%20arguments%29%3B%0A%20%20}%3B%0A}%0A%0Afunction%20_override%28object%2C%20methodName%2C%20callback%29%20{%0A%20%20object[methodName]%20%3D%20callback%28object[methodName]%29%0A}%0A%0A%2F*%0A%20*%20END%20NG-DECORATORS%20CODE%0A%20*%2F%0A%0A%0A%40Directive%28%29%0Aclass%20EditRegionsComponent%20{%0A%20%20%20%20constructor%28%29%20{%0A%20%20%20%20%20%20console.log%28%27run%27%29%0A%20%20}%0A})

**Comment by TeChn4K** [comment]
I also think this warning come from Babel.

In this [thread](https://bugzilla.mozilla.org/show_bug.cgi?id=984146), it is indicate that the use of `__proto__` produce this mutating warning.
Take a look at line 12 in this [transpile exemple](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%2F*%0A%20*%20START%20NG-DECORATORS%20CODE%0A%20*%2F%0Afunction%20Directive%28modules%20%3D%20[]%29%20{%0A%20%20return%20createDecorator%28modules%2C%20makeDirective%29%3B%0A}%0A%0Afunction%20createDecorator%28modules%2C%20makeFunction%29%20{%0A%20%20return%20%28target%29%20%3D%3E%20{%0A%20%20%20%20class%20Clazz%20extends%20target%20{%0A%20%20%20%20%20%20constructor%28...injectedValues%29%20{%0A%20%20%20%20%20%20%20%20super%28...injectedValues%29%3B%0A%20%20%20%20%20%20%20%20modules.forEach%28%28module%2C%20i%29%20%3D%3E%20{%0A%20%20%20%20%20%20%20%20%20%20this[module]%20%3D%20injectedValues[i]%3B%0A%20%20%20%20%20%20%20%20}%29%3B%0A%20%20%20%20%20%20%20%20if%20%28typeof%20this.init%20%3D%3D%3D%20%27function%27%29%20{%0A%20%20%20%20%20%20%20%20%20%20this.init%28%29%3B%0A%20%20%20%20%20%20%20%20}%0A%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20%20%20Clazz.%24inject%20%3D%20modules%3B%0A%0A%20%20%20%20return%20makeFunction%28Clazz%29%3B%0A%20%20}%0A}%0A%0Afunction%20makeDirective%28constructorFn%29%20{%0A%0A%20%20constructorFn%20%3D%20_normalizeConstructor%28constructorFn%29%3B%0A%0A%20%20if%20%28!constructorFn.prototype.compile%29%20{%0A%20%20%20%20%2F%2F%20create%20an%20empty%20compile%20function%20if%20none%20was%20defined.%0A%20%20%20%20constructorFn.prototype.compile%20%3D%20%28%29%20%3D%3E%20{%0A%20%20%20%20}%3B%0A%20%20}%0A%0A%20%20var%20originalCompileFn%20%3D%20_cloneFunction%28constructorFn.prototype.compile%29%3B%0A%0A%20%20%2F%2F%20Decorate%20the%20compile%20method%20to%20automatically%20return%20the%20link%20method%20%28if%20it%20exists%29%0A%20%20%2F%2F%20and%20bind%20it%20to%20the%20context%20of%20the%20constructor%20%28so%20%60this%60%20works%20correctly%29.%0A%20%20%2F%2F%20This%20gets%20around%20the%20problem%20of%20a%20non-lexical%20%22this%22%20which%20occurs%20when%20the%20directive%20class%20itself%0A%20%20%2F%2F%20returns%20%60this.link%60%20from%20within%20the%20compile%20function.%0A%20%20_override%28constructorFn.prototype%2C%20%27compile%27%2C%20function%20%28%29%20{%0A%20%20%20%20return%20function%20%28%29%20{%0A%20%20%20%20%20%20originalCompileFn.apply%28this%2C%20arguments%29%3B%0A%0A%20%20%20%20%20%20if%20%28constructorFn.prototype.link%29%20{%0A%20%20%20%20%20%20%20%20return%20constructorFn.prototype.link.bind%28this%29%3B%0A%20%20%20%20%20%20}%0A%20%20%20%20}%3B%0A%20%20}%29%3B%0A%0A%20%20var%20factoryArray%20%3D%20_createFactoryArray%28constructorFn%29%3B%0A%20%20return%20factoryArray%0A}%0A%0Afunction%20_normalizeConstructor%28input%29%20{%0A%20%20var%20constructorFn%3B%0A%0A%20%20if%20%28input.constructor%20%3D%3D%3D%20Array%29%20{%0A%20%20%20%20%2F%2F%0A%20%20%20%20var%20injected%20%3D%20input.slice%280%2C%20input.length%20-%201%29%3B%0A%20%20%20%20constructorFn%20%3D%20input[input.length%20-%201]%3B%0A%20%20%20%20constructorFn.%24inject%20%3D%20injected%3B%0A%20%20}%20else%20{%0A%20%20%20%20constructorFn%20%3D%20input%3B%0A%20%20}%0A%0A%20%20return%20constructorFn%3B%0A}%0A%0Afunction%20_createFactoryArray%28constructorFn%29%20{%0A%20%20%2F%2F%20get%20the%20array%20of%20dependencies%20that%20are%20needed%20by%20this%20component%20%28as%20contained%20in%20the%20%60%24inject%60%20array%29%0A%20%20var%20args%20%3D%20constructorFn.%24inject%20||%20[]%3B%0A%20%20var%20factoryArray%20%3D%20args.slice%28%29%3B%20%2F%2F%20create%20a%20copy%20of%20the%20array%0A%20%20%2F%2F%20The%20factoryArray%20uses%20Angular%27s%20array%20notation%20whereby%20each%20element%20of%20the%20array%20is%20the%20name%20of%20a%0A%20%20%2F%2F%20dependency%2C%20and%20the%20final%20item%20is%20the%20factory%20function%20itself.%0A%20%20factoryArray.push%28%28...args%29%20%3D%3E%20{%0A%20%20%20%20%2F%2Freturn%20new%20constructorFn%28...args%29%3B%0A%20%20%20%20var%20instance%20%3D%20new%20constructorFn%28...args%29%3B%0A%20%20%20%20for%20%28var%20key%20in%20instance%29%20{%0A%20%20%20%20%20%20instance[key]%20%3D%20instance[key]%3B%0A%20%20%20%20}%0A%20%20%20%20return%20instance%3B%0A%20%20}%29%3B%0A%0A%20%20return%20factoryArray%3B%0A}%0A%0Afunction%20_cloneFunction%28original%29%20{%0A%20%20return%20function%20%28%29%20{%0A%20%20%20%20return%20original.apply%28this%2C%20arguments%29%3B%0A%20%20}%3B%0A}%0A%0Afunction%20_override%28object%2C%20methodName%2C%20callback%29%20{%0A%20%20object[methodName]%20%3D%20callback%28object[methodName]%29%0A}%0A%0A%2F*%0A%20*%20END%20NG-DECORATORS%20CODE%0A%20*%2F%0A%0A%0A%40Directive%28%29%0Aclass%20EditRegionsComponent%20{%0A%20%20%20%20constructor%28%29%20{%0A%20%20%20%20%20%20console.log%28%27run%27%29%0A%20%20}%0A})

**Comment by cmartin81** [comment]
Thanks for checking this out! Then Babel is making this issue when you extend a class.
